[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "bitbucket.org/creachadair/shell"
  version = "0.0.1"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.24.0"

[[constraint]]
  name = "contrib.go.opencensus.io/exporter/stackdriver"
  version = "0.5.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.7"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/certificate-transparency-go"
  version = "1.0.19"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3"

[[constraint]]
  name = "github.com/letsencrypt/pkcs11key"
  version = "2.0.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.14.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"
